name: CI/CD Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VERSION: 1.8.0

jobs:
  terraform-apply:
    name: Terraform Init, Plan & Apply
    runs-on: ubuntu-latest
    environment:
      name: apply-approval
    outputs:
      ec2_ip: ${{ steps.extract.outputs.ec2_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/envs/dev
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform apply -auto-approve

      - name: Extract EC2 Public IP
        id: extract
        working-directory: terraform/envs/dev
        run: |
          echo "ec2_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: terraform-apply

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Get EC2 Instance ID
        id: get-instance-id
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Project,Values=springboot-devops" "Name=tag:Environment,Values=dev" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
          echo "Found instance ID: $INSTANCE_ID"

      - name: Wait for SSM Agent to be ready
        run: |
          echo "Waiting for SSM Agent to be ready on instance ${{ steps.get-instance-id.outputs.instance_id }}..."
          # Wait for up to 5 minutes for the instance to be ready for SSM commands
          timeout=300
          interval=10
          elapsed=0
          
          while [ $elapsed -lt $timeout ]; do
            STATUS=$(aws ssm describe-instance-information \
              --filters "Key=InstanceIds,Values=${{ steps.get-instance-id.outputs.instance_id }}" \
              --query "InstanceInformationList[0].PingStatus" \
              --output text 2>/dev/null || echo "NotReady")
              
            if [ "$STATUS" = "Online" ]; then
              echo "SSM Agent is online and ready!"
              break
            fi
            
            echo "Waiting for SSM Agent to come online... ($elapsed/$timeout seconds)"
            sleep $interval
            elapsed=$((elapsed + interval))
          done
          
          if [ $elapsed -ge $timeout ]; then
            echo "Timed out waiting for SSM Agent to be ready"
            exit 1
          fi

      - name: Deploy to EC2 via SSM
        run: |
          echo "Deploying to instance ${{ steps.get-instance-id.outputs.instance_id }}"
          
          # Run a simple test command first to verify SSM is working
          echo "Testing SSM with a simple command..."
          TEST_COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ steps.get-instance-id.outputs.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":["echo \"SSM Test: Hello World\"", "whoami", "pwd"]}' \
            --output text \
            --query "Command.CommandId")
          
          echo "Test SSM Command ID: $TEST_COMMAND_ID"
          
          # Wait a moment for the command to execute
          sleep 10
          
          # Check test command status
          aws ssm list-commands \
            --command-id "$TEST_COMMAND_ID" \
            --query "Commands[0].Status"
          
          # Create SSM document with deployment commands
          echo "Running deployment commands..."
          
          # Step 1: Stop and remove existing container
          echo "Step 1: Stop and remove existing container"
          STOP_COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ steps.get-instance-id.outputs.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":["docker --version", "docker stop springboot-app || echo \"No container to stop\"", "docker rm springboot-app || echo \"No container to remove\""]}' \
            --output text \
            --query "Command.CommandId")
          
          sleep 10
          
          # Step 2: Pull and run Docker Hub image with debugging
          echo "Step 2: Pull and run Docker Hub image with debugging"
          DEPLOY_COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ steps.get-instance-id.outputs.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "docker pull teeboss/springboot-demo:new || echo \"Docker pull failed\"", 
              "echo \"Running container in debug mode first...\"",
              "docker run --name springboot-debug teeboss/springboot-demo:new echo \"Testing if container can start\"",
              "docker rm springboot-debug",
              "echo \"Now running actual container...\"",
              "docker run -d -p 8080:8080 --restart always --name springboot-app teeboss/springboot-demo:new",
              "echo \"Container started with ID: $(docker ps -a --filter name=springboot-app --format {{.ID}})\"",
              "sleep 3",
              "echo \"Container status:\"",
              "docker ps -a --filter name=springboot-app --format \"{{.Image}} {{.Status}} {{.Names}}\"",
              "echo \"Container logs:\"",
              "docker logs springboot-app || echo \"No logs available\"",
              "echo \"Checking port 8080:\"",
              "netstat -tulpn | grep 8080 || echo \"Port 8080 not in use\""]}' \
            --output text \
            --query "Command.CommandId")
          
          echo "Deployment Command ID: $DEPLOY_COMMAND_ID"
          
          # Wait a bit longer for the deployment to complete
          sleep 30
          
          # Check command status
          echo "Checking command status:"
          aws ssm list-commands \
            --command-id "$DEPLOY_COMMAND_ID" \
            --query "Commands[0].Status"
          
          # Try to get command output even if it failed
          echo "Command output (if available):"
          aws ssm list-command-invocations \
            --command-id "$DEPLOY_COMMAND_ID" \
            --details \
            --query "CommandInvocations[0].CommandPlugins[0].Output" \
            --output text || echo "Could not retrieve command output"

  terraform-destroy:
    name: Terraform Destroy (Manual Approval)
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: always()
    environment:
      name: destroy-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terminate EC2 Instances First
        run: |
          # Find and terminate EC2 instances with the project tag
          INSTANCE_IDS=$(aws ec2 describe-instances \
            --filters "Name=tag:Project,Values=springboot-devops" "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text)
          
          if [ -n "$INSTANCE_IDS" ]; then
            echo "Terminating instances: $INSTANCE_IDS"
            aws ec2 terminate-instances --instance-ids $INSTANCE_IDS
            
            # Wait for instances to terminate
            echo "Waiting for instances to terminate..."
            aws ec2 wait instance-terminated --instance-ids $INSTANCE_IDS
          else
            echo "No running instances found"
          fi

      - name: Terraform Destroy
        working-directory: terraform/envs/dev
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform destroy -auto-approve