name: CI/CD Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VERSION: 1.8.0

jobs:
  terraform-apply:
    name: Terraform Init, Plan & Apply
    runs-on: ubuntu-latest
    environment:
      name: apply-approval
    outputs:
      ec2_ip: ${{ steps.extract.outputs.ec2_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/envs/dev
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform apply -auto-approve

      - name: Extract EC2 Public IP
        id: extract
        working-directory: terraform/envs/dev
        run: |
          echo "ec2_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
  docker-build-deploy:
    name: Build, Test, Push Docker to ECR & Deploy
    runs-on: ubuntu-latest
    needs: terraform-apply
    outputs:
      image_uri: ${{ steps.build.outputs.image_uri }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Test with Maven
        working-directory: ./repo-root/springboot-app/springboot-demo
        run: mvn clean package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Public ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and Push Docker Image to Public ECR
        id: build
        run: |
          export TAG=$(date +%s)
          export IMAGE_URI="public.ecr.aws/b1c8y0o0/springboot-demo:$TAG"
          docker build -t $IMAGE_URI \
            -f ./repo-root/springboot-app/springboot-demo/dockerfile \
            ./repo-root/springboot-app/springboot-demo
          docker push $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
      - name: Check Port Usage on EC2
        run: |
          # Get instance ID from IP address
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=ip-address,Values=${{ needs.terraform-apply.outputs.ec2_ip }}" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
          
          echo "Found instance ID: $INSTANCE_ID"
          
          # Check what's using port 8080
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[\"sudo lsof -i :8080\", \"sudo netstat -tulpn | grep 8080\", \"ps aux | grep -i jenkins\"]" \
            --output text
            
      - name: Deploy to EC2 via AWS SSM
        run: |
          # Get instance ID from IP address
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=ip-address,Values=${{ needs.terraform-apply.outputs.ec2_ip }}" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
          
          # Kill any process using port 8080
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[\"sudo fuser -k 8080/tcp || true\"]" \
            --output text
          
          # Deploy the application with detailed diagnostics
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[\
              \"echo 'Stopping and removing existing container...'\", \
              \"docker stop springboot-app || true\", \
              \"docker rm springboot-app || true\", \
              \"echo 'Pulling image...'\", \
              \"docker pull ${IMAGE_URI} || echo 'Failed to pull image'\", \
              \"echo 'Docker images available:'\", \
              \"docker images\", \
              \"echo 'Running container...'\", \
              \"docker run -d -p 8080:8080 --name springboot-app ${IMAGE_URI} || echo 'Failed to start container'\", \
              \"echo 'Docker processes:'\", \
              \"docker ps -a\", \
              \"echo 'Docker system info:'\", \
              \"docker info\", \
              \"echo 'Disk space:'\", \
              \"df -h\"\
            ]" \
            --output text
        env:
          IMAGE_URI: ${{ steps.build.outputs.image_uri }}
            
      - name: Verify Container is Running
        run: |
          # Get instance ID from IP address
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=ip-address,Values=${{ needs.terraform-apply.outputs.ec2_ip }}" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
          
          # Check container status
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[\
              \"echo 'Container Status:'\", \
              \"docker ps -a | grep springboot-app\", \
              \"echo 'Container Logs:'\", \
              \"docker logs springboot-app\", \
              \"echo 'Application Health Check:'\", \
              \"curl -v http://localhost:8080\"\
            ]" \
            --output text
        env:
          IMAGE_URI: ${{ steps.build.outputs.image_uri }}

  terraform-destroy:
    name: Terraform Destroy (Manual Approval)
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: always()
    environment:
      name: destroy-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/envs/dev
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform destroy -auto-approve